language: java
jdk: oraclejdk8
install: true
services:
  - mysql
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS digitaljournal;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('asdf') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - cd DigitalJournal
  - mvn clean install
  - mvn cobertura:cobertura

after_success:
    - bash <(curl -s https://codecov.io/bash)