language: java
jdk: oraclejdk8
install: true
services:
  - mysql
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS digitaljournal;'
  - sudo mysql
  - ALTER USER 'root' IDENTIFIED BY 'asdf';
  - FLUSH PRIVILEGES;
  - exit;
script:
  - cd DigitalJournal
  - mvn clean install; cobertura:cobertura

after_success:
    - bash <(curl -s https://codecov.io/bash)