language: java
jdk: oraclejdk8
install: true
services:
  - mysql
addons:
  sonarcloud:
    organization: "digitaljournal" # the key of the org you chose at step #3
    token:
      secure: "fcVAtPiu5TL0IRvOHalG+5gcIMWIwy6VfnHlhYyOBVwT2yWXE5+4t2LZ+e2yMj7sKG8Z2ZxI9+kYvOK4cdfxbvQceirnVQt+gBuqwWYR4dicN2perJYvVgFNWPcvga7Uywigrq9XZk5tnvy0rEgQVcCLl+oIiUK09+kin3U3VPoxImhTl+hD75WV2GxUl7Y28EjbF68nokypfPFDDIQyMN+ZqER3jPIGrVmHIdPqqtL/MfNv3oQ0+KczS7IpluTIY+FeCpE8YTyfMVDnvJe6yoPQdQ0xKrLC2XXkTPLYy29ygS9iawzXxrR05394bf7S5ouqIg2NfcLXlMmpysmVMtq9WZRdSupYpNo1MzRSpNKRZZGDdx4lqv045w1lDj4iUNZxt5VrfJWLJ/AA29qKhVG9Ni/kiyjNeBs8BT3XRFSpbOcFvasJ6DPSkHwcZOlxvuo9MF5MH6+lAQF3/+J37NR/ErDsxsl5Z20zprh0QRFA6VHBUGFX3C3u2SF8JtVh3EepTS1yqjQ3G+IqvObc99ojeRPMwjOkXKsuwa4YWcdlhQQiHleKMFxZZWhlWBUMeFUUIn+CRzSVl5/L7YQJYgCfn86/teUbgEswlGSpz7+yc3AZ4NxdFHzGrDMn157BY8idd1V7ZPokUhKygDbyCbYmvMxDyb2qsmf28rgib94="
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS digitaljournal;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('asdf') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - cd DigitalJournal
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
    - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: "m7XjGd+zuLX6juIzXJus6RoCebmxOB7KoGEe1/YKoWqwI6p0/Wlx+EsFPf+fonacaa7QIuCcwx5Bw9IA8sk9dn4XQBTk0iLD2XGrFKn4HoiKaY8b+bbZRgZRqNXw8A7p9dH4OX2jZs+h89BDtNC6r3RMJq72AnDKF4Na9i4kAiePRYDlz/wSIkn8L9wdmtj6ExbJUUUvNDzEmRVHg8a3m9KRpnyjYj1yFtI0flQnqGCVZ6z9k/vgbuREICQo9FLwtav38gFns4dO6bBfh9JccuRFg3c2ORNJdZ8mYIBhGRW9nzXWLl3r4hvLy3TOYa+/KW1au8QB67V+xZMW4zruTs0BIaOKs8GAWT2ZEVfOVsjC0P4wLbwye9sdbabVheFnKtXg5/4IP3VqqFBoIS5aWDdIo/EJYQg10Wn/BiZct6TvqbE4Y3u/L/2OLvAkh3kMSFB2/yuHlOBS3IhgxXsicXNv3FuWGBWMqwdjyEm1X/oIgH6fl18UuF6IhnW3RmKKHB245fxvPJMLaCaZew2ijMBr9tLwcQ5NDdLA9igyt6tUL8yTkagbzP0sXOk/a0EOg0W4ofBc6K57sD8Xgfd9Jug+t0azzdWgYjSG6dDyAW76OQjOHgWfUxSN1W+xMS/XgKps+ClhtA0VAE6pKXAUGcntYJ2lxtsaaQ9VXO9gyxo="
  file: "digitaljournal-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
